select * from customer;
--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue 
from customer
group by gender;

--Q2. Which customer used a discount but still spent more than the average amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and
purchase_amount >= (select avg(purchase_amount) from customer);

--Q3. Which are the TOP 5 products with highest average review ratings?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Ratings"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare average purchase amount between Standard and Express shipping.
Select shipping_type,AVG(purchase_amount) as Average_Amount
from customer
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spent and total revenue between subscribers and non-subscribers?
select COUNT(customer_id) as total_customer, subscription_status,Round(AVG(purchase_amount::numeric),2) as Average_Parchase_amount,SUM(purchase_amount) as Total_Purchase_Amount
from customer
group by subscription_status;

--Q6. Which 5 products have highest percentage of purchases with discounts applied?
select item_purchased as products, 
Round(100* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q6. Segment customers into new, returning and loyal based on their previous purchases, also show the count of each segment.
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT customer_segment, count(*) as "Number of Customers"
FROM customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?
with item_count as (select category, 
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)

select item_rank,category, item_purchased
from item_count
where item_rank <= 3;

--Q9. Are custmers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>=5
group by subscription_status;

--Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount)
from customer
group by age_group;
